---
title: "Resume"
output: html_document
hidedate: true
hiderelated: true
hidediscus: true
---

# **Alejandra Plazola**

|aplazola48@gmail.com| 
Phone:512-318-1792|
linkedin.com/in/alejandra-plazola|
Del Valle, Tx 78617|

## **EDUCATION**
### **University of Texas at Austin						| Spring 2021**
B.S.A in Biology: College of Natural Sciences

Composite Science Certificate: UTeach, College of Natural Sciences

Certified to teach grades 7-12 and subjects: Biology, Chemistry, Geology, and Physics.
 
Google Certified Educator:Level 1

## **EXPERIENCE**
 
### **UT International Office 						| Sept.2018-May 2019**
### **Credit Team Assistant**

Assist the Credit Team transfer student’s foreign credit into UT credit. 

Translate transcripts, translate foreign grades into UT grades, input student information in an excel sheets.
Send emails to students and faculty about classes, transcripts, and credit

File and folder student’s information

Update the study abroad credit database

### **Environmental Science Institute			| Sept.2019-Dec. 2019**
### **ESI Intern**
Create lesson plans for Guest Speaker’s talks/lectures
Edit and research about lesson plans

Help with ESI’s new website giving suggestions as a perspective of a teacher/student

Create worksheets and activities that went with lesson plans

### **Breakthrough						| Jan.2020-Aug. 2020**
### **Breakthrough Intern						| Jan.2020-Mar.2020**
Office work, organizing office, data work, clerical tasks. 

Tutoring/Mentoring Students in math/science. 

Support Breakthrough staff

### **Summer Teaching Fellow					| Jun.2020-Aug.2020**
Zoom summer program: Taught and lead a group of rising 8th graders from the Manor ISD area in a team of 3. (Team 6)

Teacher/Mentor for Middle School students.

Lead faculty events, student events, hosting office hours.

Create lesson plans, PowerPoint, assignments, working with google classroom, google site artifact of entire summer. Link:<https://sites.google.com/view/btcxt-virtual-summer-2020/welcome>  

Creating own electives (Tiktok).

Parent and student outreach. 

#### **Breakthrough Get’s Fit Committee**
Help create and lead fun activities that involve physical activities for the students.

Working in a team to in order to create the event and plan activities. 

Share a mental wellness, physical exercise, or health tip at all school events.

## **ORGANIZATIONS**
 
### **University Leadership Network			|Aug.2017-Present**
A 4-year leadership organization to help students get involved in networking and gaining experience.

Helps student leadership skills and discuss good leadership qualities.

Help students gain internships and studying abroad opportunities.

Scholarship. 

### **Kappa Delta Chi Sorority Inc.			|Feb.2019-Present**
A Latina/Hispanic Sorority that provides professional networking and gaining leadership opportunities that provide community service to the local/national community.

Assisting in organizing and planning events.

Developing Professional Skills.

**Stroll Co-Chair (Fall 2019 and Spring 2020) **
Leading sisters in dance practices, learning choreography, and strolls.

Creating Choreography and cutting music and putting music together. 

**Service Committee Member (Fall 2019)**
Assisting Service Chair with annual KDChi Autumn Fest, which is our fall service event. 

**Fundraising Committee Member (Spring 2020)**

**Alumnae Relations Chair (Fall 2020)** 
Planning an Alumni Event with Alumni sisters and undergrad sisters. Lead alumni events, outreach with alumni sisters. Update Alumni Roster/Contacts.


## **SKILLS**
 
**Languages:** Proficient in English and Spanish

**Software:** MS: Office: Word, Power point, Excel. R Studio. iMovie. Loom. Zoom. Google Classroom. Google Drive, Docs, Sheets, Forms, Sites, Calendar. 

**Social media:** Facebook, Snapchat, Instagram, Twitter. 


